name: mobile_booking_online_doctor
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  cupertino_icons: ^1.0.8
  dartz: ^0.10.1
  dio: ^5.4.0
  flutter:
    sdk: flutter
  flutter_map: ^6.1.0
  flutter_screenutil: ^5.9.3
  flutter_svg: ^2.2.0
  geocoding: ^2.2.0
  geolocator: ^10.1.0
  get_it: ^8.2.0
  flutter_bloc: ^9.1.1
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  path_provider: ^2.1.5
  google_fonts: ^6.3.0
  http: ^1.4.0
  intl_phone_field: ^3.2.0
  latlong2: ^0.9.1
  pin_code_fields: ^8.0.1
  shared_preferences: ^2.5.3
  smooth_page_indicator: ^1.1.0

dev_dependencies:
  flutter_launcher_icons: ^0.14.4
  flutter_lints: ^6.0.0
  flutter_test:
    sdk: flutter
  hive_generator: 2.0.1
  build_runner: ^2.4.13

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icons/heart.png"

flutter:
  uses-material-design: true

  assets:
  - assets/icons/
  - assets/svgs/
  - assets/images/
  - assets/images/onboarding_images/
  - assets/fonts/montserrat/
  - assets/fonts/georgia/

  fonts:
  - family: Montserrat
    fonts:
    - asset: assets/fonts/montserrat/Montserrat-ExtraBold.ttf
      weight: 800
    - asset: assets/fonts/montserrat/Montserrat-Bold.ttf
      weight: 700
    - asset: assets/fonts/montserrat/Montserrat-SemiBold.ttf
      weight: 600
    - asset: assets/fonts/montserrat/Montserrat-Medium.ttf
      weight: 500
    - asset: assets/fonts/montserrat/Montserrat-Regular.ttf
      weight: 400

  - family: Georgia
    fonts:
    - asset: assets/fonts/georgia/georgia-bold.ttf
      weight: 700
    - asset: assets/fonts/georgia/georgia-regular.ttf
      weight: 400

flutter_assets:
  assets_path: assets/
  output_path: lib/core/helpers/
  filename: assets.dart
